name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DOCKER_USERNAME: adipurnomo
  SHORT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Access to Docker Registry
      - name: Login to Docker Registry
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: docker.io
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Setup Base URL
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "BASE_URL"
          replace: "env.BASE_URL"
          include: "api/controllers/UrlController.js"

      # Setup Database Host
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "DATABASE_HOST"
          replace: "env.DATABASE_HOST"
          include: "config/env/*.js"

      # Setup Database Name
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "DATABASE_NAME"
          replace: "env.DATABASE_NAME"
          include: "config/env/*.js"

      # Setup Database Password
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "DATABASE_PASSWORD"
          replace: "secrets.DATABASE_PASSWORD"
          include: "config/env/*.js"

      # Build Image
      - uses: actions/checkout@v3
      - name: Build the image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}

      # Push Image
      - name: Push the image
        run: docker push ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}

      # Deploy Image
      - name: Deploy to Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/project3
            sed -i '8s|.*|    image: ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:${{ env.SHORT_SHA }}|' docker-compose.yml
            docker-compose down
            docker-compose up -d
            docker ps -a
